Speisekarte-main/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Speisekarte.Data;
using Speisekarte.Models;
using System.Diagnostics;

namespace Speisekarte.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ApplicationDbContext _context;

        public HomeController(ILogger<HomeController> logger, ApplicationDbContext context)
        {
            _logger = logger;
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            // Informationen für eine Drop-Down-Liste bereitstellen
            List<SelectListItem> selectListItems = new List<SelectListItem>();
            SelectListItem eintrag0 = new SelectListItem("Very Good", "5");
            selectListItems.Add(eintrag0);
            SelectListItem eintrag = new SelectListItem("Good", "4");
            selectListItems.Add(eintrag);
            SelectListItem eintrag2 = new SelectListItem("Medium", "3");
            selectListItems.Add(eintrag2);
            SelectListItem eintrag3 = new SelectListItem("Not Good", "2");
            selectListItems.Add(eintrag3);
            SelectListItem eintrag4 = new SelectListItem("Awful", "1");
            selectListItems.Add(eintrag4);
            // Die Übergabe erfolgt über das ViewData-Dictionary
            ViewData["Kategorien"] = selectListItems;
            //Wenn != null dann wird view zurückgegeben sonst Problem Darstellungen 
            return _context.Speisen != null ? View(await _context.Speisen.Include(speise => speise.Zutaten).ToListAsync()) :
                Problem("Entity set ApplicationDBContext.Speisen is null");

        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult AddZutatForm(int? id)
        {
            if (id is not null && id > 0)
            {
                var speiseFromDb = _context.Speisen.FirstOrDefault(s => s.Id == id);
                if (speiseFromDb != null)
                {
                    Zutat zutat = new Zutat();
                    zutat.SpeiseId = id;
                    return View(zutat);
                }
            }
            return View();
        }

        public IActionResult addZutat(Zutat zutat)
        {
            if(zutat.SpeiseId != null && zutat.SpeiseId > 0)
            {
                Speise? speiseFromDb = _context.Speisen.FirstOrDefault(x => x.Id == zutat.SpeiseId);
                if(speiseFromDb != null)
                {
                    speiseFromDb.Zutaten.Add(zutat);
                    _context.SaveChanges();
                }

            }
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> CreateSpeiseForm()
        {
            // Informationen für eine Drop-Down-Liste bereitstellen
            List<SelectListItem> selectListItems = new List<SelectListItem>();
            SelectListItem eintrag0 = new SelectListItem("Very Good", "5");
            selectListItems.Add(eintrag0);
            SelectListItem eintrag = new SelectListItem("Good", "4");
            selectListItems.Add(eintrag);
            SelectListItem eintrag2 = new SelectListItem("Medium", "3");
            selectListItems.Add(eintrag2);
            SelectListItem eintrag3 = new SelectListItem("Not Good", "2");
            selectListItems.Add(eintrag3);
            SelectListItem eintrag4 = new SelectListItem("Awful", "1");
            selectListItems.Add(eintrag4);
            // Die Übergabe erfolgt über das ViewData-Dictionary
            ViewData["Kategorien"] = selectListItems;
            //Wenn != null dann wird view zurückgegeben sonst Problem Darstellungen 
            return View();

        }
        public IActionResult CreateSpeise(Speise speise)
        {
            if (speise is not null)
            {
                _context.Speisen.Add(speise);
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Speisekarte-main/Controllers/ValuesController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Speisekarte.Data;
using Speisekarte.Models;

namespace Speisekarte.Controllers
{
    [Route("api/[controller]")]
    [ApiController]
    public class ValuesController : ControllerBase
    {
        private readonly ApplicationDbContext _context;

        public ValuesController(ApplicationDbContext context)
        {
            _context = context;
        }

        [HttpPost]
        [Route("Fill")]
        public void FillData()
        {
            Speise s1 = new Speise{Titel = "Hauptspeise",Notizen = "Meine Notizen",Sterne = 3};
            Zutat z1 = new Zutat{Beschreibung = "Mehl",Einheit = "g",Menge = 200};
            Zutat z2 = new Zutat{ Beschreibung = "Zucker",Einheit = "g", Menge = 100};
            Zutat z3 = new Zutat { Beschreibung = "Öl",Einheit = "ml",Menge = 200};

            s1.Zutaten.Add(z1);
            s1.Zutaten.Add(z2);
            s1.Zutaten.Add(z3);



            Speise s2 = new Speise { Titel = "Schnitzel", Notizen = "Meine Notizen", Sterne = 25 };
            z1 = new Zutat { Beschreibung = "Mehl", Einheit = "g", Menge = 200 };
            z2 = new Zutat { Beschreibung = "Eier", Einheit = "Anzahl", Menge = 3 };
            z3 = new Zutat { Beschreibung = "Öl", Einheit = "ml", Menge = 200 };

            s2.Zutaten.Add(z1);
            s2.Zutaten.Add(z2);
            s2.Zutaten.Add(z3);

            _context.Speisen.Add(s1);
            _context.Speisen.Add(s2);
            _context.SaveChanges();
        }

        [HttpGet]
        [Route("GetAll")]
        public List<Speise> GetSpeisen()
        {
            var speisen = _context.Speisen
                .Include(speise => speise.Zutaten)
                .ToList();
            return speisen;
        }

        [HttpGet]
        [Route("GetTop")]
        public List<Top> GetTopSpeisen()
        {
            var speisen = _context.Speisen
                    .OrderByDescending(speise => speise.Sterne)
                    .Take(3)
                    .ToList();

            List<Top> top = new List<Top>();
            foreach(Speise speise in speisen)
            {
                Top instance = new Top();
                instance.Titel = speise.Titel;
                instance.Sterne = speise.Sterne;
                top.Add(instance);

            }
            return top;
        }


        [HttpDelete("Delete")]
        public async Task<IActionResult> Delete(int? id)
        {
            if(id == null || _context.Speisen == null)
            {
                return NotFound();
            }
            var speise = await _context.Speisen
                .Include(speise => speise.Zutaten)
                .FirstOrDefaultAsync(x => x.Id == id);

            if(speise == null)
            {
                return NotFound();
            }

            foreach(Zutat zutat in speise.Zutaten)
            {
                _context.Zutaten.Remove(zutat);
            }

            _context.Speisen.Remove(speise);
            await _context.SaveChangesAsync();
            return NoContent();



        }
    }
}

Speisekarte-main/Views/Home/AddZutatForm.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Zutat
<h1>Zutat hinzufügen</h1>
<div class="row">
    <div class="col-md-4">
        <form asp-controller="Home" asp-action="AddZutat">
            <div class="card">
                
                <div class="card-body">
                    <input hidden asp-for="SpeiseId" />
                    <div class="row mb-3">
                        <div class="col">
                            <input class="form-control" asp-for="Beschreibung" type="text" placeholder="Beschreibung" />
                            <span asp-validation-for="Beschreibung" class="text-danger"></span>
                        </div>
                    </div>
                    <div class="row mb-3">
                        <div class="col">
                            <label>Einheit</label>
                            <input class="form-control" asp-for="Einheit" type="text" placeholder="Einheit" />
                            <span asp-validation-for="Einheit" class="text-danger"></span>
                        </div>
                        <div class="col">
                            <label>Menge</label>
                            <input class="form-control" asp-for="Menge" type="text" placeholder="Menge" />
                            <span asp-validation-for="Menge" class="text-danger"></span>
                        </div>
                    </div>

                </div>
                <div class="card-footer">
                    <button class="btn btn-primary" type="submit">Speichern</button>
                </div>
            </div>
           
        </form>
    </div>
</div>

@section Scripts{
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Speisekarte-main/Views/Home/CreateSpeiseForm.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Speise

<form asp-controller="Home" asp-action="CreateSpeise">
    <div class="card">
        <div class="card-header">
            <h5>Speise hinzufügen</h5>
        </div>
        <div class="card-body">
            <div class="row mb-3">
                <div class="col">
                    <input class="form-control" asp-for="Titel" type="text" placeholder="Titel" />
                </div>
            </div>
            <div class="row mb-3">
                <div class="col">
                    <textarea class="form-control" asp-for="Notizen" type="text" placeholder="Ausführliche Beschreibung"></textarea>
                </div>
                <div class="col">
                    <select asp-for="Sterne" form-control" asp-items="@((IEnumerable<SelectListItem>)ViewData["Kategorien"])"></select>
                </div>
            </div>
           
        </div>
        <div class="card-footer">
            <button class="btn btn-primary" type="submit">Speichern</button>
        </div>
    </div>
</form>

Speisekarte-main/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

@model List<Speise>
<div class="row d-flex justify-content-center text-center">
    <h1 class="display-4">Speisen</h1>
    <a asp-controller="Home" asp-action="CreateSpeiseForm">Neue Speise anlegen</a>
    @if (ViewData["Kategorien"] is not null)
    {
        var elem = ViewData["Kategorien"] as IEnumerable<SelectListItem>;
        if (elem is not null)
        {
            foreach (var n in elem)
            {
                <li>@n.Text ist @n.Value</li>
            }
            <br />
            <label class="control-label">Kategorien: </label>
            <select form-control" asp-items="elem"></select>
        }
    }
    <br />

    <div class="form-group">
        <!-- <label class="control-label">Kategorien: </label> -->
        <!--<select asp-for="item.Sterne" form-control" asp-items="@((IEnumerable<SelectListItem>)ViewData["Kategorien"])"></select> -->
    </div>
    <hr />

    @{
        foreach (Speise speise in Model)
        {
                <div class="card" style="width: 30rem; margin: 1rem">
                    <div class="card-body">
                    <h4 class="card-text"><b>@speise.Titel</b></h4>
                    <p class="card-text" style="text-align: start"><b>Beschreibung:</b> @speise.Notizen</p>
                    <p class="card-text" style="text-align: start"><b>Sterne:</b> @speise.Sterne</p>
                    @{
                        for(int i = 0; i < speise.Sterne; i++)
                        {
                            <img src="./images/Star_29.png" heigt="20" width="30" />
                        }
                    }
                    <p class="card-text" style="text-align: start"><b>Zutaten:</b> </p>
                        <table class="table">
                            <thead>
                                <tr>
                                    <td>Beschreibung</td>
                                    <td>Menge</td>
                                    <td>Einheit</td>
                                </tr>
                            </thead>
                            <tbody>
                               
                                @{
                                foreach (Zutat zutat in speise.Zutaten)
                                {
                                            <tr>
                                                <td>@Html.DisplayFor(zutatItem => zutat.Beschreibung)</td>
                                                <td>@zutat.Menge</td>
                                                <td>@zutat.Einheit</td>
                                            </tr>
                                }
                                }
                                
                            </tbody> 
                        </table>
                        <button type="button" class="btn btn-danger" onclick="onDeleteClicked(@speise.Id)">
                            Delete
                        </button>
                    <a asp-controller="Home" asp-action="AddZutatForm" class="btn btn-primary" asp-route-id="@speise.Id">Neue Zutat </a>
                    </div>

                </div>
        }
    }
    
    
</div>




@section Scripts {

    <script>
        

        function onDeleteClicked(id) {
            //Frage den Benutzer
            del = confirm("Wollen Sie wirklich löschen?");
            if (del) {
            //Backend call
            $.ajax({
                type: "DELETE",
                    url: "@Url.Action("Delete", "Values")" + "?id=" + id,
                //data: { id: id },
                success: function (msg) {
                    alert("Ok, wurde gelöscht");
                    location.reload();
                },
                error: function (msg) {
                    alert("Fehler beim Löschen");
                }

            });

            }
           

        }


    </script>
}